# Generated by Django 6.0 on 2026-01-12 21:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu nhập')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại vật tư')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã VT')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Đơn vị')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nhà cung cấp')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='SĐT')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
            ],
        ),
        migrations.CreateModel(
            name='InputVoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_lot_no', models.CharField(blank=True, max_length=50, verbose_name='Lot NCC')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Khối lượng (kg)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Đơn giá (VND)')),
                ('si_test', models.FloatField(default=0, verbose_name='Si (%)')),
                ('fe_test', models.FloatField(default=0, verbose_name='Fe (%)')),
                ('cu_test', models.FloatField(default=0, verbose_name='Cu (%)')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='warehouse_input.inputvoucher')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.materialtype', verbose_name='Loại hàng')),
            ],
        ),
        migrations.AddField(
            model_name='inputvoucher',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.supplier', verbose_name='Nhà cung cấp'),
        ),
    ]
