# Generated by Django 6.0 on 2025-12-06 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại vật tư')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Đơn vị tính')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
            ],
        ),
        migrations.CreateModel(
            name='InputVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày giờ nhập')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Biển số xe')),
                ('spectro_file', models.FileField(blank=True, null=True, upload_to='spectro_reports/%Y/%m/', verbose_name='Kết quả Spectro (PDF/Ảnh)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú thêm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.supplier', verbose_name='Nhà cung cấp')),
            ],
        ),
    ]
