# Generated by Django 6.0 on 2025-12-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputVoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Khối lượng (kg)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá / kg')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.materialtype', verbose_name='Loại hàng')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='warehouse_input.inputvoucher')),
            ],
        ),
    ]
