# Generated by Django 6.0 on 2026-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputvoucher',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='inputvoucherdetail',
            name='supplier_lot_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lot NCC'),
        ),
        migrations.AddField(
            model_name='inputvoucherdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Đơn giá (VND)'),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='SĐT'),
        ),
    ]
