# Generated by Django 6.0 on 2026-01-18 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhóm')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Nhóm vật tư',
                'verbose_name_plural': 'Nhóm vật tư',
            },
        ),
        migrations.AddField(
            model_name='materialtype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_types', to='warehouse_input.materialcategory', verbose_name='Thuộc nhóm'),
        ),
    ]
