# Generated by Django 6.0 on 2026-01-12 21:45

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_input', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlloyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên Mác Nhôm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả đặc tính')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã KH')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Khách Hàng')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Mã vạch')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KL Tịnh')),
                ('is_odd', models.BooleanField(default=False, verbose_name='Kiện lẻ')),
                ('status', models.CharField(choices=[('NEW', 'Tồn kho'), ('SOLD', 'Đã bán')], default='NEW', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnace_name', models.CharField(max_length=50, verbose_name='Lò nấu')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COOKING', 'Đang nấu'), ('DONE', 'Hoàn thành')], default='COOKING', max_length=20)),
                ('si_final', models.FloatField(default=0, verbose_name='Si Final')),
                ('fe_final', models.FloatField(default=0, verbose_name='Fe Final')),
                ('cu_final', models.FloatField(default=0, verbose_name='Cu Final')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu xuất')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày xuất')),
                ('note', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.customer', verbose_name='Khách hàng')),
                ('bundles', models.ManyToManyField(related_name='deliveries', to='production.finishedbundle', verbose_name='Danh sách kiện')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialIssueDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KL Thực (Kg)')),
                ('status', models.CharField(choices=[('WAITING', 'Đã cân/Chờ lò'), ('CHARGED', 'Đã nạp lò'), ('RETURN', 'Trả lại kho')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.inputvoucherdetail', verbose_name='Lấy từ Lô Nhập')),
            ],
        ),
        migrations.CreateModel(
            name='FurnaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('ADD', 'Nạp Liệu'), ('TEST', 'Test Mẫu')], default='ADD', max_length=20)),
                ('adhoc_weight', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0, verbose_name='Nhiệt độ')),
                ('test_result_note', models.TextField(blank=True, verbose_name='KQ Test')),
                ('adhoc_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_input.materialtype')),
                ('issue_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.materialissuedetail')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='production.productionbatch')),
            ],
        ),
        migrations.AddField(
            model_name='finishedbundle',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionbatch'),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=50, unique=True, verbose_name='LOT NO (Mã Lô)')),
                ('target_quantity', models.FloatField(default=0, verbose_name='Sản lượng yêu cầu (Kg)')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lập lệnh')),
                ('status', models.CharField(choices=[('NEW', 'Mới tạo'), ('PROCESSING', 'Đang sản xuất'), ('DONE', 'Đã đóng Lô')], default='NEW', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú SX')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.customer', verbose_name='Khách hàng')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.alloytype', verbose_name='Sản phẩm (Mác nhôm)')),
            ],
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.productionorder', verbose_name='Sản xuất cho LotNo'),
        ),
        migrations.AddField(
            model_name='materialissuedetail',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_issues', to='production.productionorder', verbose_name='Thuộc LotNo'),
        ),
        migrations.CreateModel(
            name='HistoricalProductionBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('furnace_name', models.CharField(max_length=50, verbose_name='Lò nấu')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COOKING', 'Đang nấu'), ('DONE', 'Hoàn thành')], default='COOKING', max_length=20)),
                ('si_final', models.FloatField(default=0, verbose_name='Si Final')),
                ('fe_final', models.FloatField(default=0, verbose_name='Fe Final')),
                ('cu_final', models.FloatField(default=0, verbose_name='Cu Final')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionorder', verbose_name='Sản xuất cho LotNo')),
            ],
            options={
                'verbose_name': 'historical production batch',
                'verbose_name_plural': 'historical production batchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.FloatField(verbose_name='Khối lượng cần (Kg)')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.materialtype', verbose_name='Loại liệu cần')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Tiêu chuẩn')),
                ('si_min', models.FloatField(default=0, verbose_name='Si Min')),
                ('si_max', models.FloatField(default=0, verbose_name='Si Max')),
                ('fe_min', models.FloatField(default=0, verbose_name='Fe Min')),
                ('fe_max', models.FloatField(default=0, verbose_name='Fe Max')),
                ('cu_min', models.FloatField(default=0, verbose_name='Cu Min')),
                ('cu_max', models.FloatField(default=0, verbose_name='Cu Max')),
                ('notes', models.TextField(blank=True, verbose_name='Quy cách tem/đóng gói')),
                ('alloy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.alloytype', verbose_name='Mác nhôm áp dụng')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.customer', verbose_name='Khách hàng')),
            ],
            options={
                'unique_together': {('customer', 'alloy_type')},
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productstandard', verbose_name='Tiêu chuẩn áp dụng'),
        ),
        migrations.CreateModel(
            name='RepackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu xử lý')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('input_bundles', models.ManyToManyField(related_name='repacked_in', to='production.finishedbundle', verbose_name='Kiện nguồn')),
            ],
        ),
        migrations.CreateModel(
            name='WeighingSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu cân TP')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionorder', verbose_name='Cân cho LotNo')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.materialtype')),
                ('weighing_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='production.weighingslip')),
            ],
        ),
        migrations.AddField(
            model_name='finishedbundle',
            name='weighing_slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='production.weighingslip'),
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Tháng (YYYY-MM)')),
                ('planned_quantity', models.FloatField(default=0, verbose_name='Kế hoạch (Kg)')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_input.materialtype', verbose_name='Loại vật tư')),
            ],
            options={
                'unique_together': {('month', 'material_type')},
            },
        ),
    ]
