# Generated by Django 6.0 on 2025-12-08 17:59

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_input', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã KH')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Khách Hàng')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=50, unique=True, verbose_name='Lot No')),
                ('furnace_name', models.CharField(max_length=50, verbose_name='Lò nấu')),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bắt đầu')),
                ('status', models.CharField(choices=[('COOKING', 'Đang nấu'), ('DONE', 'Hoàn thành')], default='COOKING', max_length=20)),
                ('total_slag', models.IntegerField(default=0, verbose_name='Xỉ (Gầu)')),
                ('gas_usage', models.FloatField(default=0, verbose_name='Gas (kg)')),
            ],
        ),
        migrations.CreateModel(
            name='FurnaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('ADD', 'Nạp Liệu'), ('TEST', 'Test Mẫu')], max_length=10, verbose_name='Hành động')),
                ('quantity', models.FloatField(default=0, verbose_name='Khối lượng (kg)')),
                ('si_result', models.FloatField(default=0, verbose_name='Si Result')),
                ('note', models.TextField(blank=True)),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_input.materialtype')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='production.productionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Tiêu chuẩn')),
                ('alloy_type', models.CharField(max_length=50, verbose_name='Mác nhôm')),
                ('si_min', models.FloatField(default=0, verbose_name='Si Min')),
                ('si_max', models.FloatField(default=0, verbose_name='Si Max')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.customer', verbose_name='Khách hàng')),
            ],
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='target_standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productstandard', verbose_name='Tiêu chuẩn'),
        ),
        migrations.CreateModel(
            name='HistoricalProductionBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('lot_no', models.CharField(db_index=True, max_length=50, verbose_name='Lot No')),
                ('furnace_name', models.CharField(max_length=50, verbose_name='Lò nấu')),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bắt đầu')),
                ('status', models.CharField(choices=[('COOKING', 'Đang nấu'), ('DONE', 'Hoàn thành')], default='COOKING', max_length=20)),
                ('total_slag', models.IntegerField(default=0, verbose_name='Xỉ (Gầu)')),
                ('gas_usage', models.FloatField(default=0, verbose_name='Gas (kg)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_standard', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productstandard', verbose_name='Tiêu chuẩn')),
            ],
            options={
                'verbose_name': 'historical production batch',
                'verbose_name_plural': 'historical production batchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WeighingSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionbatch', verbose_name='Thuộc LotNo')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.materialtype')),
                ('weighing_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='production.weighingslip')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_odd', models.BooleanField(default=False, verbose_name='Kiện lẻ')),
                ('status', models.CharField(choices=[('NEW', 'Mới'), ('SOLD', 'Đã bán')], default='NEW', max_length=20)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='production.productionbatch')),
                ('weighing_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='production.weighingslip')),
            ],
        ),
    ]
