# Generated by Django 6.0 on 2025-12-08 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu xuất')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày xuất')),
                ('note', models.TextField(blank=True)),
                ('bundles', models.ManyToManyField(related_name='deliveries', to='production.finishedbundle', verbose_name='Danh sách kiện xuất')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.customer', verbose_name='Khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='RepackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu xử lý')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú (VD: Ghép 2 kiện lẻ)')),
                ('input_bundles', models.ManyToManyField(related_name='repacked_in', to='production.finishedbundle', verbose_name='Kiện nguồn (Bị hủy)')),
            ],
        ),
    ]
