# Generated by Django 6.0 on 2026-01-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_deliverynote_repackingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingslip',
            name='ng_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TL Hàng NG'),
        ),
        migrations.AddField(
            model_name='weighingslip',
            name='pallet_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='TL Chân đế'),
        ),
    ]
