# Generated by Django 6.0 on 2025-12-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tồn kho thực tế')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_input.materialtype', verbose_name='Loại vật tư')),
            ],
        ),
    ]
