# Generated by Django 6.0 on 2026-01-12 21:07

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_input', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventoryItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tồn kho thực tế')),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mức an toàn')),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse_input.materialtype', verbose_name='Loại vật tư')),
            ],
            options={
                'verbose_name': 'historical inventory item',
                'verbose_name_plural': 'historical inventory items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tồn kho thực tế')),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mức an toàn')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_input.materialtype', verbose_name='Loại vật tư')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu kiểm kê')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjustment_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lượng điều chỉnh (+/-)')),
                ('reason', models.TextField(verbose_name='Lý do chênh lệch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.materialtype', verbose_name='Vật tư')),
            ],
        ),
    ]
