# Generated by Django 6.0 on 2025-12-08 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_input', '0001_initial'),
        ('warehouse_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu kiểm kê')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjustment_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lượng điều chỉnh (+/-)')),
                ('reason', models.TextField(verbose_name='Lý do chênh lệch')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_input.materialtype', verbose_name='Vật tư')),
            ],
        ),
    ]
