# Generated by Django 6.0 on 2026-01-04 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_stock', '0002_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
