# Generated by Django 6.0 on 2025-12-05 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại nhôm')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả/Tiêu chuẩn')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=50, unique=True, verbose_name='Mã Lot (LotNo)')),
                ('production_date', models.DateField(verbose_name='Ngày sản xuất')),
                ('total_input_weight', models.FloatField(default=0, verbose_name='Tổng KL Nguyên liệu vào (kg)')),
                ('total_output_weight', models.FloatField(default=0, verbose_name='Tổng KL Thành phẩm ra (kg)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu nấu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc nấu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Loại sản phẩm')),
            ],
        ),
    ]
