# Generated by Django 6.0 on 2025-12-06 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên công ty/Khách hàng')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã KH')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
            ],
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='total_output_weight',
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer', verbose_name='Dành cho KH'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(max_length=50, verbose_name='Mã kiện (VD: 01, 02...)')),
                ('weight', models.FloatField(verbose_name='Khối lượng tịnh (Kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian cân')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productionbatch', verbose_name='Thuộc Lot No')),
            ],
            options={
                'verbose_name': 'Phiếu cân / Kiện hàng',
                'verbose_name_plural': 'Danh sách Phiếu cân',
                'unique_together': {('batch', 'package_code')},
            },
        ),
    ]
